language: scala
jdk:
  - openjdk8
  - openjdk11
scala:
  - 2.12.8
  - 2.13.0-M5
env:
  - AKKA_VERSION=
  - AKKA_VERSION=2.5.19
matrix:
  exclude:
  - scala: 2.13.0-M5
    env: AKKA_VERSION=2.5.19
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport -Dakka.version=$AKKA_VERSION
after_success:
  - bash <(curl -s https://codecov.io/bash)
