language: scala
jdk:
  - openjdk8
  - openjdk11
  - openjdk14
scala:
  - 2.11.12
  - 2.12.11
  - 2.13.3
env:
  - AKKA_VERSION=2.5.31
  - AKKA_VERSION=2.6.6
matrix:
  exclude:
  - scala: 2.11.12
    env: AKKA_VERSION=2.6.6
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport -Dakka.version=$AKKA_VERSION
after_success:
  - bash <(curl -s https://codecov.io/bash)
